name: awal
on:   
  push:
  
jobs:
  run-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, A.2]
        flag: [A, B, C, D, E, F, G, H, I, J]
    steps: 
      - uses: actions/checkout@v4
      - name: running
        continue-on-error: true
        run: echo hello
